-- 코드를 입력하세요
SELECT DATE_FORMAT(S.SALES_DATE, '%Y') YEAR,
       DATE_FORMAT(S.SALES_DATE, '%m') MONTH,
       COUNT(DISTINCT S.USER_ID) PURCHASED_USER,
       round(COUNT(DISTINCT S.USER_ID) 
             / (SELECT COUNT(user_id)
                FROM user_info
                WHERE DATE_FORMAT(joined, '%Y') = '2021'), 1) PURCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE DATE_FORMAT(I.JOINED, "%Y") = "2021"
GROUP BY YEAR, MONTH