# -- 코드를 입력하세요
# SELECT F.FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER
# FROM FIRST_HALF AS F
# JOIN JULY AS J
# ON F.FLAVOR = J.FLAVOR
# GROUP BY FLAVOR

# SELECT *
# FROM FIRST_HALF

# SELECT *
# FROM JULY

# SELECT *, SUM(J.TOTAL_ORDER), F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) AS TOTAL
# FROM FIRST_HALF AS F
# JOIN JULY AS J
# ON F.FLAVOR = J.FLAVOR
# GROUP BY J.FLAVOR
# ORDER BY TOTAL DESC
# LIMIT 0,3

SELECT A.FLAVOR
FROM (
    SELECT F.FLAVOR, SUM(J.TOTAL_ORDER), F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF AS F
    JOIN JULY AS J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY J.FLAVOR
) AS A
ORDER BY A.TOTAL DESC
LIMIT 0,3

