SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS A
JOIN (
    SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER (ORDER BY R.CNT DESC) AS RANKING
    FROM (
        SELECT *, COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ) AS R
    JOIN MEMBER_PROFILE AS M
    ON M.MEMBER_ID = R.MEMBER_ID
) AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.RANKING = 1
ORDER BY REVIEW_DATE